"""Schema de l'entite Operation.

Ce fichier definit le schema complet pour les operations
de sauvetage maritime.

Pour ajouter un nouveau champ:
1. Ajouter un FieldSchema dans la liste fields
2. Specifier la section appropriee
3. Ajouter l'enum_ref si necessaire (dans enums.py)
"""

from src.schema.definitions import (
    EntitySchema,
    FieldSchema,
    FormSection,
    WidgetType,
)

OPERATION_SCHEMA = EntitySchema(
    name="operation",
    model_class="Operation",
    crud_instance="crud_operation",
    primary_key="operation_id",
    display_name="Operation",
    display_name_plural="Operations",
    sections=[
        FormSection(
            name="identification",
            label="Identification",
            columns=2,
            order=1,
        ),
        FormSection(
            name="alerte",
            label="Alerte SECMAR",
            columns=2,
            collapsible=True,
            expanded=False,
            order=2,
        ),
        FormSection(
            name="localisation",
            label="Localisation",
            columns=2,
            order=3,
        ),
        FormSection(
            name="contexte",
            label="Contexte operation",
            columns=2,
            collapsible=True,
            expanded=False,
            order=4,
        ),
        FormSection(
            name="meteo",
            label="Conditions meteo",
            columns=4,
            collapsible=True,
            expanded=False,
            order=5,
        ),
        FormSection(
            name="temporel",
            label="Donnees temporelles",
            columns=2,
            collapsible=True,
            expanded=False,
            order=6,
        ),
        FormSection(
            name="enrichissement",
            label="Donnees enrichies",
            columns=3,
            collapsible=True,
            expanded=False,
            order=7,
        ),
    ],
    fields=[
        # =====================================================================
        # Section: Identification
        # =====================================================================
        FieldSchema(
            name="operation_id",
            label="ID Operation",
            widget=WidgetType.NUMBER_INPUT,
            required=True,
            min_value=1,
            step=1,
            help_text="Identifiant unique de l'operation",
            section="identification",
            order=1,
            visible_in_list=True,
            list_order=1,
            editable=True,  # Editable en creation, desactive en edition via disabled_fields
        ),
        FieldSchema(
            name="numero_sitrep",
            label="Numero SITREP",
            widget=WidgetType.TEXT_INPUT,
            max_chars=50,
            help_text="Numero du rapport SITREP",
            section="identification",
            order=2,
            visible_in_list=False,
        ),
        FieldSchema(
            name="cross_sitrep",
            label="CROSS SITREP",
            widget=WidgetType.TEXT_INPUT,
            max_chars=100,
            help_text="Identifiant composite CROSS-annee",
            section="identification",
            order=3,
            visible_in_list=False,
        ),
        FieldSchema(
            name="date_operation",
            label="Date de l'operation",
            widget=WidgetType.DATE_INPUT,
            help_text="Date de l'intervention",
            section="identification",
            order=3,
            visible_in_list=True,
            list_order=2,
        ),
        FieldSchema(
            name="heure_operation",
            label="Heure",
            widget=WidgetType.TIME_INPUT,
            help_text="Heure de debut de l'intervention",
            section="identification",
            order=4,
            visible_in_list=False,
        ),
        FieldSchema(
            name="type_operation",
            label="Type d'operation",
            widget=WidgetType.SELECTBOX,
            enum_ref="TYPE_OPERATION",
            help_text="Type principal de l'operation",
            section="identification",
            order=5,
            visible_in_list=True,
            list_order=3,
        ),
        FieldSchema(
            name="sous_type_operation",
            label="Sous-type",
            widget=WidgetType.TEXT_INPUT,
            max_chars=100,
            help_text="Sous-categorie de l'operation",
            section="identification",
            order=6,
            visible_in_list=False,
        ),
        FieldSchema(
            name="cross",
            label="CROSS",
            widget=WidgetType.SELECTBOX,
            enum_ref="CROSS_VALUES",
            help_text="Centre Regional de coordination",
            section="identification",
            order=8,
            visible_in_list=True,
            list_order=4,
        ),
        # =====================================================================
        # Section: Alerte SECMAR
        # =====================================================================
        FieldSchema(
            name="pourquoi_alerte",
            label="Pourquoi alerte",
            widget=WidgetType.TEXT_INPUT,
            max_chars=100,
            help_text="Raison du declenchement de l'alerte",
            section="alerte",
            order=1,
            visible_in_list=False,
        ),
        FieldSchema(
            name="moyen_alerte",
            label="Moyen d'alerte",
            widget=WidgetType.TEXT_INPUT,
            max_chars=100,
            help_text="Canal de transmission de l'alerte",
            section="alerte",
            order=2,
            visible_in_list=False,
        ),
        FieldSchema(
            name="qui_alerte",
            label="Qui alerte",
            widget=WidgetType.TEXT_INPUT,
            max_chars=100,
            help_text="Entite signalante",
            section="alerte",
            order=3,
            visible_in_list=False,
        ),
        FieldSchema(
            name="categorie_qui_alerte",
            label="Categorie alertant",
            widget=WidgetType.TEXT_INPUT,
            max_chars=100,
            help_text="Classification du lanceur d'alerte",
            section="alerte",
            order=4,
            visible_in_list=False,
        ),
        # =====================================================================
        # Section: Localisation
        # =====================================================================
        FieldSchema(
            name="departement",
            label="Departement",
            widget=WidgetType.TEXT_INPUT,
            max_chars=3,
            help_text="Code departement (ex: 56, 2A)",
            section="localisation",
            order=1,
            visible_in_list=True,
            list_order=5,
        ),
        FieldSchema(
            name="zone_responsabilite",
            label="Zone de responsabilite",
            widget=WidgetType.TEXT_INPUT,
            max_chars=50,
            section="localisation",
            order=2,
            visible_in_list=False,
        ),
        FieldSchema(
            name="latitude",
            label="Latitude",
            widget=WidgetType.NUMBER_INPUT,
            min_value=-90.0,
            max_value=90.0,
            step=0.000001,
            format_str="%.6f",
            help_text="Latitude WGS84 (-90 a 90)",
            section="localisation",
            order=3,
            visible_in_list=False,
        ),
        FieldSchema(
            name="longitude",
            label="Longitude",
            widget=WidgetType.NUMBER_INPUT,
            min_value=-180.0,
            max_value=180.0,
            step=0.000001,
            format_str="%.6f",
            help_text="Longitude WGS84 (-180 a 180)",
            section="localisation",
            order=4,
            visible_in_list=False,
        ),
        FieldSchema(
            name="est_metropolitain",
            label="Metropolitain",
            widget=WidgetType.CHECKBOX,
            default=True,
            help_text="France metropolitaine",
            section="localisation",
            order=5,
            visible_in_list=False,
        ),
        # =====================================================================
        # Section: Contexte operation
        # =====================================================================
        FieldSchema(
            name="evenement",
            label="Evenement",
            widget=WidgetType.TEXT_INPUT,
            max_chars=100,
            help_text="Type d'incident",
            section="contexte",
            order=1,
            visible_in_list=False,
        ),
        FieldSchema(
            name="categorie_evenement",
            label="Categorie evenement",
            widget=WidgetType.TEXT_INPUT,
            max_chars=100,
            help_text="Regroupement thematique",
            section="contexte",
            order=2,
            visible_in_list=False,
        ),
        FieldSchema(
            name="autorite",
            label="Autorite",
            widget=WidgetType.TEXT_INPUT,
            max_chars=100,
            help_text="Autorite en charge",
            section="contexte",
            order=3,
            visible_in_list=False,
        ),
        FieldSchema(
            name="seconde_autorite",
            label="Seconde autorite",
            widget=WidgetType.TEXT_INPUT,
            max_chars=100,
            help_text="Autorite secondaire",
            section="contexte",
            order=4,
            visible_in_list=False,
        ),
        # =====================================================================
        # Section: Meteo
        # =====================================================================
        FieldSchema(
            name="vent_direction",
            label="Direction vent",
            widget=WidgetType.NUMBER_INPUT,
            min_value=0,
            max_value=360,
            step=1,
            help_text="Direction en degres (0-360)",
            section="meteo",
            order=1,
            visible_in_list=False,
        ),
        FieldSchema(
            name="vent_force",
            label="Force vent",
            widget=WidgetType.NUMBER_INPUT,
            min_value=0,
            max_value=12,
            step=1,
            help_text="Echelle Beaufort (0-12)",
            section="meteo",
            order=2,
            visible_in_list=False,
        ),
        FieldSchema(
            name="mer_force",
            label="Etat de mer",
            widget=WidgetType.NUMBER_INPUT,
            min_value=0,
            max_value=9,
            step=1,
            help_text="Echelle Douglas (0-9)",
            section="meteo",
            order=3,
            visible_in_list=False,
        ),
        FieldSchema(
            name="vent_direction_categorie",
            label="Direction vent (categorie)",
            widget=WidgetType.SELECTBOX,
            enum_ref="VENT_DIRECTION_CATEGORIE",
            help_text="Orientation cardinale du vent",
            section="meteo",
            order=4,
            visible_in_list=False,
        ),
        # =====================================================================
        # Section: Temporel
        # =====================================================================
        FieldSchema(
            name="date_heure_reception_alerte",
            label="Reception alerte",
            widget=WidgetType.DATE_INPUT,
            help_text="Date/heure de reception de l'alerte",
            section="temporel",
            order=1,
            visible_in_list=False,
        ),
        FieldSchema(
            name="date_heure_fin_operation",
            label="Fin operation",
            widget=WidgetType.DATE_INPUT,
            help_text="Date/heure de fin de l'operation",
            section="temporel",
            order=2,
            visible_in_list=False,
        ),
        FieldSchema(
            name="fuseau_horaire",
            label="Fuseau horaire",
            widget=WidgetType.TEXT_INPUT,
            max_chars=50,
            help_text="Fuseau horaire IANA (ex: Europe/Paris)",
            section="temporel",
            order=3,
            visible_in_list=False,
        ),
        FieldSchema(
            name="systeme_source",
            label="Systeme source",
            widget=WidgetType.TEXT_INPUT,
            max_chars=50,
            help_text="Systeme informatique source",
            section="temporel",
            order=4,
            visible_in_list=False,
        ),
        # =====================================================================
        # Section: Enrichissement (MCD)
        # =====================================================================
        FieldSchema(
            name="prefecture_maritime",
            label="Prefecture maritime",
            widget=WidgetType.SELECTBOX,
            enum_ref="PREFECTURE_MARITIME",
            help_text="Zone de prefecture maritime",
            section="enrichissement",
            order=1,
            visible_in_list=False,
        ),
        FieldSchema(
            name="phase_journee",
            label="Phase de journee",
            widget=WidgetType.SELECTBOX,
            enum_ref="PHASE_JOURNEE",
            help_text="Moment de la journee",
            section="enrichissement",
            order=2,
            visible_in_list=False,
        ),
        FieldSchema(
            name="distance_cote_metres",
            label="Distance cote (m)",
            widget=WidgetType.NUMBER_INPUT,
            min_value=0,
            step=100,
            help_text="Distance de la cote en metres",
            section="enrichissement",
            order=3,
            visible_in_list=False,
        ),
        FieldSchema(
            name="distance_cote_milles_nautiques",
            label="Distance cote (NM)",
            widget=WidgetType.NUMBER_INPUT,
            min_value=0.0,
            step=0.1,
            format_str="%.2f",
            help_text="Distance de la cote en milles nautiques",
            section="enrichissement",
            order=4,
            visible_in_list=False,
        ),
        FieldSchema(
            name="est_jour_ferie",
            label="Jour ferie",
            widget=WidgetType.CHECKBOX,
            default=False,
            section="enrichissement",
            order=5,
            visible_in_list=False,
        ),
        FieldSchema(
            name="est_vacances_scolaires",
            label="Vacances scolaires",
            widget=WidgetType.CHECKBOX,
            default=False,
            section="enrichissement",
            order=6,
            visible_in_list=False,
        ),
        FieldSchema(
            name="concerne_plongee",
            label="Concerne plongee",
            widget=WidgetType.CHECKBOX,
            default=False,
            section="enrichissement",
            order=7,
            visible_in_list=False,
        ),
        FieldSchema(
            name="implique_wingfoil",
            label="Implique wingfoil",
            widget=WidgetType.CHECKBOX,
            default=False,
            section="enrichissement",
            order=8,
            visible_in_list=False,
        ),
        FieldSchema(
            name="est_dans_stm",
            label="Dans STM",
            widget=WidgetType.CHECKBOX,
            default=False,
            help_text="Service de Trafic Maritime",
            section="enrichissement",
            order=9,
            visible_in_list=False,
        ),
        FieldSchema(
            name="nom_stm",
            label="Nom STM",
            widget=WidgetType.TEXT_INPUT,
            max_chars=100,
            section="enrichissement",
            order=10,
            visible_in_list=False,
        ),
        FieldSchema(
            name="est_dans_dst",
            label="Dans DST",
            widget=WidgetType.CHECKBOX,
            default=False,
            help_text="Dispositif de Separation du Trafic",
            section="enrichissement",
            order=11,
            visible_in_list=False,
        ),
        FieldSchema(
            name="nom_dst",
            label="Nom DST",
            widget=WidgetType.TEXT_INPUT,
            max_chars=100,
            section="enrichissement",
            order=12,
            visible_in_list=False,
        ),
        FieldSchema(
            name="maree_port",
            label="Port de reference maree",
            widget=WidgetType.TEXT_INPUT,
            max_chars=100,
            section="enrichissement",
            order=13,
            visible_in_list=False,
        ),
        FieldSchema(
            name="maree_coefficient",
            label="Coefficient maree",
            widget=WidgetType.NUMBER_INPUT,
            min_value=20,
            max_value=120,
            step=1,
            section="enrichissement",
            order=14,
            visible_in_list=False,
        ),
        FieldSchema(
            name="maree_categorie",
            label="Categorie maree",
            widget=WidgetType.SELECTBOX,
            enum_ref="MAREE_CATEGORIE",
            section="enrichissement",
            order=15,
            visible_in_list=False,
        ),
    ],
)
